[package]
name = "svgize"
version = "0.1.0"
edition = "2021"
authors = ["Charles Dong <charlesdong_2000@outlook.com>"]
readme = "./README.md"
repository = "https://github.com/chardon55/svgize.git"
homepage = "https://github.com/chardon55/svgize"
license = "MIT"
description = "Fast and safe SVG encoder"

[features]
default = ["attr_core", "attr_styling"]

attr_core = []
attr_styling = []
attr_event = []
attr_prest = []
attr_cond_proc = []

cross_origin = []

# Experimental SVG standard 
exp = []

ns_xml = []
ns_xlink = []

deprecated = []

[dependencies]
quick-xml = "0.31"

